apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: project-frontend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 80
      name: frontend