apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-dep
  namespace: logger-ponger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - name: logger
          image: okisma/logger:2.01
          resources:
            limits:
              cpu: "300m"
              memory: "500Mi"
          envFrom:
            - secretRef:
                name: db-secrets