apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/secret.yaml
- manifests/database.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/ingress.yaml
images:
- name: gcr.io/PROJECT_ID/BACKEND_IMAGE
  newName: gcr.io/project/project-backend
  newTag: "3.03"
