apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: project-backend
  ports:
    - port: 4567
      protocol: TCP
      targetPort: 3001
      name: backend