apiVersion: v1
kind: Service
metadata:
  name: ponger-svc
  namespace: logger-ponger
spec:
  type: NodePort
  selector:
    app: ponger
  ports:
    - port: 4567
      protocol: TCP
      targetPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: logger-svc
  namespace: logger-ponger
spec:
  type: NodePort
  selector:
    app: logger
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3002