apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: project-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: cpu-usage-rate
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      volumes:
        - name: image-cache
          emptyDir: {}
      containers:
        - name: project-backend
          image: okisma/project-backend:4.02
          volumeMounts:
          - name: image-cache
            mountPath: /usr/src/app/public
          envFrom:
            - secretRef:
                name: db-secrets
          ports:
            - containerPort: 3001
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 3001
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 3001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-frontend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-frontend
  template:
    metadata:
      labels:
        app: project-frontend
    spec:
      containers:
        - name: project-frontend
          image: okisma/project-frontend:4.02