apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: project-backend
  ports:
    - port: 4567
      protocol: TCP
      targetPort: 3001
      name: backend

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: project-frontend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 80
      name: frontend