apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-frontend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-frontend
  template:
    metadata:
      labels:
        app: project-frontend
    spec:
      containers:
        - name: project-frontend
          image: okisma/project-frontend:2.02