apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-dep
  namespace: logger-ponger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - name: logger
          image: okisma/logger:2.01