apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      volumes:
        - name: image-cache
          emptyDir: {}
      containers:
        - name: project-backend
          image: BACKEND_IMAGE
          volumeMounts:
          - name: image-cache
            mountPath: /usr/src/app/public
          envFrom:
            - secretRef:
                name: db-secrets
          env:
            - name: NATS_URL
              value: nats://nats.default:4222
          ports:
            - containerPort: 3001
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 3001
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 3001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-frontend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-frontend
  template:
    metadata:
      labels:
        app: project-frontend
    spec:
      containers:
        - name: project-frontend
          image: FRONTEND_IMAGE

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-broadcaster
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-broadcaster
  template:
    metadata:
      labels:
        app: project-broadcaster
    spec:
      containers:
        - name: project-broadcaster
          image: BROADCASTER_IMAGE
          env:
            - name: NATS_URL
              value: nats://nats.default:4222
            - name: BROADCAST_URL
              value: http://backend-svc:4567/msg