apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- database.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: BACKEND_IMAGE
  newName: okisma/project-backend
  newTag: ebfc37cb9a8246324409a97dc148141edc7044c3
- name: BROADCASTER_IMAGE
  newName: okisma/project-broadcaster
  newTag: ebfc37cb9a8246324409a97dc148141edc7044c3
- name: FRONTEND_IMAGE
  newName: okisma/project-frontend
  newTag: ebfc37cb9a8246324409a97dc148141edc7044c3
