apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- database.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: BACKEND_IMAGE
  newName: okisma/project-backend
  newTag: 54bf992803cbb001e0d3b74127ca06571e019ec2
- name: BROADCASTER_IMAGE
  newName: okisma/project-broadcaster
  newTag: 54bf992803cbb001e0d3b74127ca06571e019ec2
- name: FRONTEND_IMAGE
  newName: okisma/project-frontend
  newTag: 54bf992803cbb001e0d3b74127ca06571e019ec2
