apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-writer-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader-writer
  template:
    metadata:
      labels:
        app: reader-writer
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
      containers:
        - name: reader
          image: okisma/reader:1.10
          volumeMounts:
          - name: shared-log
            mountPath: /usr/src/app/files
        - name: writer
          image: okisma/writer:1.10
          volumeMounts:
          - name: shared-log
            mountPath: /usr/src/app/files